[package]
name = "plugin-cli"
version = "0.1.0"
edition = "2021"
exclude = ["index.js"]

[[bin]]
name = "plugin-cli"
path = "src/main.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
flate2 = "1"
glob = "0.3"
home = "0.5"
ignore = "0.4"
inquire = "0.7"
keyring = { version = "2", default-features = false, features = [
    "byteorder",
    "linux-keyutils",
    "linux-secret-service",
    "linux-secret-service-rt-tokio-crypto-rust",
    "platform-all",
    "platform-linux",
    "platform-macos",
    "platform-windows",
    "security-framework",
    "windows-sys",
] }
liquid = "0.26"
owo-colors = "4"
reqwest = { version = "0.12", features = ["blocking", "multipart", "json"] }
semver = { version = "1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
tar = "0.4"
thiserror = "2"
fs_extra = "1"
strum = "0.27"
strum_macros = "0.27"

shared = { git = "https://git.aaa-soft.net/CMS/Radiant.git", branch = "fix/pluginsystem-rework-improvements" }
